language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t manisha/docker-react-new -f Dockerfile.dev .

script:
  - docker run manisha/docker-react-new npm run test -- --coverage
